insert into dbo.DocumentType (Version, Code, Name) values (1,21,N'Паспорт гражданина Российской Федерации')
insert into dbo.DocumentType (Version, Code, Name) values (1,12,N'Вид на жительство')
insert into dbo.DocumentType (Version, Code, Name) values (1,27,N'Военный билет офицера запаса')
insert into dbo.DocumentType (Version, Code, Name) values (1,07,N'Военный билет солдата (матроса, сержанта, старшины)')
insert into dbo.DocumentType (Version, Code, Name) values (1,14,N'Временное удостоверение личности гражданина Российской Федерации')
insert into dbo.DocumentType (Version, Code, Name) values (1,09,N'Дипломатический паспорт гражданина Российской Федерации')
insert into dbo.DocumentType (Version, Code, Name) values (1,22,N'Загранпаспорт гражданина Российской Федерации')
insert into dbo.DocumentType (Version, Code, Name) values (1,02,N'Загранпаспорт гражданина СССР')
insert into dbo.DocumentType (Version, Code, Name) values (1,91,N'Иные документы')
insert into dbo.DocumentType (Version, Code, Name) values (1,01,N'Паспорт гражданина СССР')
insert into dbo.DocumentType (Version, Code, Name) values (1,10,N'Паспорт иностранного гражданина')
insert into dbo.DocumentType (Version, Code, Name) values (1,06,N'Паспорт Минморфлота')
insert into dbo.DocumentType (Version, Code, Name) values (1,26,N'Паспорт моряка')
insert into dbo.DocumentType (Version, Code, Name) values (1,15,N'Разрешение на временное проживание в Российской Федерации')
insert into dbo.DocumentType (Version, Code, Name) values (1,11,N'Свидетельство о рассмотрении ходатайства о признании беженцем на территории Российской Федерации')
insert into dbo.DocumentType (Version, Code, Name) values (1,03,N'Свидетельство о рождении')
insert into dbo.DocumentType (Version, Code, Name) values (1,23,N'Свидетельство о рождении, выданное уполномоченным органом иностранного государства')
insert into dbo.DocumentType (Version, Code, Name) values (1,05,N'Справка об освобождении из  места лишения свободы')
insert into dbo.DocumentType (Version, Code, Name) values (1,13,N'Удостоверение беженца в Российской Федерации')
insert into dbo.DocumentType (Version, Code, Name) values (1,04,N'Удостоверение личности офицера')