//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports.Presenters {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reports.Presenters.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала - обязательное поле.
        /// </summary>
        internal static string AbsenceEditModel_BeginDate_Required {
            get {
                return ResourceManager.GetString("AbsenceEditModel_BeginDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество дней (часов) - обязательное поле.
        /// </summary>
        internal static string AbsenceEditModel_DaysCount_Required {
            get {
                return ResourceManager.GetString("AbsenceEditModel_DaysCount_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания - обязательное поле.
        /// </summary>
        internal static string AbsenceEditModel_EndDate_Required {
            get {
                return ResourceManager.GetString("AbsenceEditModel_EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месяц - обязательное поле..
        /// </summary>
        internal static string ActionListModel_Month_Required {
            get {
                return ResourceManager.GetString("ActionListModel_Month_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активировать.
        /// </summary>
        internal static string ActivateButtonNameActive {
            get {
                return ResourceManager.GetString("ActivateButtonNameActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деактивировать.
        /// </summary>
        internal static string ActivateButtonNameInactive {
            get {
                return ResourceManager.GetString("ActivateButtonNameInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий - обязательное поле.
        /// </summary>
        internal static string AddCommentModel_Comment_Required {
            get {
                return ResourceManager.GetString("AddCommentModel_Comment_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия приложения: {0}.
        /// </summary>
        internal static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный User Id: {0}..
        /// </summary>
        internal static string AuthenticationService_InvalidUserID {
            get {
                return ResourceManager.GetString("AuthenticationService_InvalidUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail - обязательное поле.
        /// </summary>
        internal static string ChangePasswordModel_Email_Required {
            get {
                return ResourceManager.GetString("ChangePasswordModel_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль - обязательное поле..
        /// </summary>
        internal static string ChangePasswordModel_Password_Required {
            get {
                return ResourceManager.GetString("ChangePasswordModel_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенные пароли не совпадают..
        /// </summary>
        internal static string ConfirmPasswordCompareValidatorText {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompareValidatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия базы данных: {0}.
        /// </summary>
        internal static string DatabaseVersion {
            get {
                return ResourceManager.GetString("DatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует активность &apos;{0}&apos;..
        /// </summary>
        internal static string DefaultActionResolver_ActionIsNotMapped {
            get {
                return ResourceManager.GetString("DefaultActionResolver_ActionIsNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания Т. Д. - обязательное поле.
        /// </summary>
        internal static string DismissalEditModel_EndDate_Required {
            get {
                return ResourceManager.GetString("DismissalEditModel_EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основание документ - обязательное поле.
        /// </summary>
        internal static string DismissalEditModel_Reason_Required {
            get {
                return ResourceManager.GetString("DismissalEditModel_Reason_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация - обязательное поле.
        /// </summary>
        internal static string EditInfoModel_Message_Required {
            get {
                return ResourceManager.GetString("EditInfoModel_Message_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема - обязательное поле.
        /// </summary>
        internal static string EditInfoModel_Subject_Required {
            get {
                return ResourceManager.GetString("EditInfoModel_Subject_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название - обязательное поле.
        /// </summary>
        internal static string EditTypeModel_Name_Required {
            get {
                return ResourceManager.GetString("EditTypeModel_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст - обязательное поле.
        /// </summary>
        internal static string EmployeeDocumentEditModel_Comment_Required {
            get {
                return ResourceManager.GetString("EmployeeDocumentEditModel_Comment_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ запрещен.
        /// </summary>
        internal static string Error_AccessDeniedException {
            get {
                return ResourceManager.GetString("Error_AccessDeniedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно загрузить пользователя с id {0} из базы данных.    .
        /// </summary>
        internal static string Error_CannotLoadUserWithId {
            get {
                return ResourceManager.GetString("Error_CannotLoadUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В базе данных не найден вопрос ( id = {0}). .
        /// </summary>
        internal static string Error_QuestionLoad {
            get {
                return ResourceManager.GetString("Error_QuestionLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа в выходной /праздничный день - обязательное поле.
        /// </summary>
        internal static string HolidayWorkEditModel_Date_Required {
            get {
                return ResourceManager.GetString("HolidayWorkEditModel_Date_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во отработанных часов - обязательное поле.
        /// </summary>
        internal static string HolidayWorkEditModel_Hours_Required {
            get {
                return ResourceManager.GetString("HolidayWorkEditModel_Hours_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часовая тарифная ставка - обязательное поле.
        /// </summary>
        internal static string HolidayWorkEditModel_Rate_Required {
            get {
                return ResourceManager.GetString("HolidayWorkEditModel_Rate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша учетная запись неактивна. Свяжитесь с администратором..
        /// </summary>
        internal static string Login_AccountInactive {
            get {
                return ResourceManager.GetString("Login_AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно получить версию базы данных ..
        /// </summary>
        internal static string Login_Exception {
            get {
                return ResourceManager.GetString("Login_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильная версия базы данных.Версия приложения {0} ,версия базы данных {1}.Свяжитесь с администратором..
        /// </summary>
        internal static string Login_IncorrectDatabaseVersion {
            get {
                return ResourceManager.GetString("Login_IncorrectDatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильное имя пользователя..
        /// </summary>
        internal static string Login_LoginIncorrect {
            get {
                return ResourceManager.GetString("Login_LoginIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный пароль..
        /// </summary>
        internal static string Login_PasswordIncorrect {
            get {
                return ResourceManager.GetString("Login_PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин - обязательное поле..
        /// </summary>
        internal static string LogOnModel_Login_Required {
            get {
                return ResourceManager.GetString("LogOnModel_Login_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль - обязательное поле.
        /// </summary>
        internal static string LogOnModel_Password_Required {
            get {
                return ResourceManager.GetString("LogOnModel_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_BeginDate_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_BeginDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна, город командировки - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_Country_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_Country_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_EndDate_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Источник финансирования командировки - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_FinancesSource_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_FinancesSource_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цель командировки - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_Goal_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_Goal_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация, куда командировка - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_Organization_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_Organization_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основание командировки - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_Reason_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_Reason_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль слишком короткий..
        /// </summary>
        internal static string PasswordRegExValidatorText {
            get {
                return ResourceManager.GetString("PasswordRegExValidatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конфигурационная секция &apos;{0}&apos; не найдена..
        /// </summary>
        internal static string Section_NotFound {
            get {
                return ResourceManager.GetString("Section_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail для отправки в Биллинг - обязательное поле.
        /// </summary>
        internal static string SettingsModel_BillingEmail_Required {
            get {
                return ResourceManager.GetString("SettingsModel_BillingEmail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Логин (отправка в биллинг) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_BillingLogin_Required {
            get {
                return ResourceManager.GetString("SettingsModel_BillingLogin_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Пароль (отправка в биллинг) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_BillingPassword_Required {
            get {
                return ResourceManager.GetString("SettingsModel_BillingPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP порт (отправка в биллинг) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_BillingPort_Required {
            get {
                return ResourceManager.GetString("SettingsModel_BillingPort_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Сервер (отправка в биллинг) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_BillingSmtp_Required {
            get {
                return ResourceManager.GetString("SettingsModel_BillingSmtp_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к файлу для загрузки - обязательное поле.
        /// </summary>
        internal static string SettingsModel_DownloadDictionaryFilePath_Required {
            get {
                return ResourceManager.GetString("SettingsModel_DownloadDictionaryFilePath_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail для отправки сообщений о произведенном иморте/экспорте - обязательное поле.
        /// </summary>
        internal static string SettingsModel_ExportImportEmail_Required {
            get {
                return ResourceManager.GetString("SettingsModel_ExportImportEmail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail для отправки уведомлений - обязательное поле.
        /// </summary>
        internal static string SettingsModel_NotificationEmail_Required {
            get {
                return ResourceManager.GetString("SettingsModel_NotificationEmail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Логин (отправка уведомлений) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_NotificationLogin_Required {
            get {
                return ResourceManager.GetString("SettingsModel_NotificationLogin_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Пароль (отправка уведомлений) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_NotificationPassword_Required {
            get {
                return ResourceManager.GetString("SettingsModel_NotificationPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP порт (отправка уведомлений) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_NotificationPort_Required {
            get {
                return ResourceManager.GetString("SettingsModel_NotificationPort_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Сервер (отправка уведомлений) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_NotificationSmtp_Required {
            get {
                return ResourceManager.GetString("SettingsModel_NotificationSmtp_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата удаления сотрудников, уволенных до - обязательное поле..
        /// </summary>
        internal static string SettingsModel_ReleaseEmployeeDeleteDate_Required {
            get {
                return ResourceManager.GetString("SettingsModel_ReleaseEmployeeDeleteDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к файлу выгрузки табеля - обязательное поле.
        /// </summary>
        internal static string SettingsModel_UploadTimesheetFilePath_Required {
            get {
                return ResourceManager.GetString("SettingsModel_UploadTimesheetFilePath_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала больничного - обязательное поле.
        /// </summary>
        internal static string SicklistEditModel_BeginDate_Required {
            get {
                return ResourceManager.GetString("SicklistEditModel_BeginDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания больничного - обязательное поле.
        /// </summary>
        internal static string SicklistEditModel_EndDate_Required {
            get {
                return ResourceManager.GetString("SicklistEditModel_EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активный.
        /// </summary>
        internal static string StatusActive {
            get {
                return ResourceManager.GetString("StatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неактивный.
        /// </summary>
        internal static string StatusInactive {
            get {
                return ResourceManager.GetString("StatusInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата  - обязательное поле.
        /// </summary>
        internal static string TimesheetCorrectionEditModel_Date_Required {
            get {
                return ResourceManager.GetString("TimesheetCorrectionEditModel_Date_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часы  - обязательное поле.
        /// </summary>
        internal static string TimesheetCorrectionEditModel_Hours_Required {
            get {
                return ResourceManager.GetString("TimesheetCorrectionEditModel_Hours_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часы - обязательное поле.
        /// </summary>
        internal static string TimesheetListModel_Hours_Required {
            get {
                return ResourceManager.GetString("TimesheetListModel_Hours_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестна.
        /// </summary>
        internal static string UnknownDatabaseVersion {
            get {
                return ResourceManager.GetString("UnknownDatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин - обязательное поле.
        /// </summary>
        internal static string UserEditModel_Login_Required {
            get {
                return ResourceManager.GetString("UserEditModel_Login_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль - обязательное поле.
        /// </summary>
        internal static string UserEditModel_Password_Required {
            get {
                return ResourceManager.GetString("UserEditModel_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО - обязательное поле.
        /// </summary>
        internal static string UserEditModel_UserName_Required {
            get {
                return ResourceManager.GetString("UserEditModel_UserName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала отпуска - обязательное поле .
        /// </summary>
        internal static string VacationEditModel_BeginDate_Required {
            get {
                return ResourceManager.GetString("VacationEditModel_BeginDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания отпуска - обязательное поле.
        /// </summary>
        internal static string VacationEditModel_EndDate_Required {
            get {
                return ResourceManager.GetString("VacationEditModel_EndDate_Required", resourceCulture);
            }
        }
    }
}
