//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports.Presenters {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reports.Presenters.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала - обязательное поле.
        /// </summary>
        internal static string AbsenceEditModel_BeginDate_Required {
            get {
                return ResourceManager.GetString("AbsenceEditModel_BeginDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество дней (часов) - обязательное поле.
        /// </summary>
        internal static string AbsenceEditModel_DaysCount_Required {
            get {
                return ResourceManager.GetString("AbsenceEditModel_DaysCount_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания - обязательное поле.
        /// </summary>
        internal static string AbsenceEditModel_EndDate_Required {
            get {
                return ResourceManager.GetString("AbsenceEditModel_EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Месяц - обязательное поле..
        /// </summary>
        internal static string ActionListModel_Month_Required {
            get {
                return ResourceManager.GetString("ActionListModel_Month_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активировать.
        /// </summary>
        internal static string ActivateButtonNameActive {
            get {
                return ResourceManager.GetString("ActivateButtonNameActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Деактивировать.
        /// </summary>
        internal static string ActivateButtonNameInactive {
            get {
                return ResourceManager.GetString("ActivateButtonNameInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий - обязательное поле.
        /// </summary>
        internal static string AddCommentModel_Comment_Required {
            get {
                return ResourceManager.GetString("AddCommentModel_Comment_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия приложения: {0}.
        /// </summary>
        internal static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный User Id: {0}..
        /// </summary>
        internal static string AuthenticationService_InvalidUserID {
            get {
                return ResourceManager.GetString("AuthenticationService_InvalidUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-mail - обязательное поле.
        /// </summary>
        internal static string ChangePasswordModel_Email_Required {
            get {
                return ResourceManager.GetString("ChangePasswordModel_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль - обязательное поле..
        /// </summary>
        internal static string ChangePasswordModel_Password_Required {
            get {
                return ResourceManager.GetString("ChangePasswordModel_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введенные пароли не совпадают..
        /// </summary>
        internal static string ConfirmPasswordCompareValidatorText {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompareValidatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Баланс мес.(дней) - обязательное поле.
        /// </summary>
        internal static string ConstantEditModel_Days_Required {
            get {
                return ResourceManager.GetString("ConstantEditModel_Days_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Баланс мес.(часов) - обязательное поле.
        /// </summary>
        internal static string ConstantEditModel_Hours_Required {
            get {
                return ResourceManager.GetString("ConstantEditModel_Hours_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия базы данных: {0}.
        /// </summary>
        internal static string DatabaseVersion {
            get {
                return ResourceManager.GetString("DatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует активность &apos;{0}&apos;..
        /// </summary>
        internal static string DefaultActionResolver_ActionIsNotMapped {
            get {
                return ResourceManager.GetString("DefaultActionResolver_ActionIsNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания Т. Д. - обязательное поле.
        /// </summary>
        internal static string DismissalEditModel_EndDate_Required {
            get {
                return ResourceManager.GetString("DismissalEditModel_EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основание документ - обязательное поле.
        /// </summary>
        internal static string DismissalEditModel_Reason_Required {
            get {
                return ResourceManager.GetString("DismissalEditModel_Reason_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация - обязательное поле.
        /// </summary>
        internal static string EditInfoModel_Message_Required {
            get {
                return ResourceManager.GetString("EditInfoModel_Message_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема - обязательное поле.
        /// </summary>
        internal static string EditInfoModel_Subject_Required {
            get {
                return ResourceManager.GetString("EditInfoModel_Subject_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата СФ(акта) - обязательное поле.
        /// </summary>
        internal static string EditMissionPbDocumentModel_Date_Required {
            get {
                return ResourceManager.GetString("EditMissionPbDocumentModel_Date_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер СФ(акта) - обязательное поле.
        /// </summary>
        internal static string EditMissionPbDocumentModel_Number_Required {
            get {
                return ResourceManager.GetString("EditMissionPbDocumentModel_Number_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название - обязательное поле.
        /// </summary>
        internal static string EditTypeModel_Name_Required {
            get {
                return ResourceManager.GetString("EditTypeModel_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст - обязательное поле.
        /// </summary>
        internal static string EmployeeDocumentEditModel_Comment_Required {
            get {
                return ResourceManager.GetString("EmployeeDocumentEditModel_Comment_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала Т Д - обязательное поле.
        /// </summary>
        internal static string EmploymentEditModel_BeginDate_Required {
            get {
                return ResourceManager.GetString("EmploymentEditModel_BeginDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оклад (тарифная ставка) - обязательное поле.
        /// </summary>
        internal static string EmploymentEditModel_Salary_Required {
            get {
                return ResourceManager.GetString("EmploymentEditModel_Salary_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ запрещен.
        /// </summary>
        internal static string Error_AccessDeniedException {
            get {
                return ResourceManager.GetString("Error_AccessDeniedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно загрузить пользователя с id {0} из базы данных.    .
        /// </summary>
        internal static string Error_CannotLoadUserWithId {
            get {
                return ResourceManager.GetString("Error_CannotLoadUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В базе данных не найден вопрос ( id = {0}). .
        /// </summary>
        internal static string Error_QuestionLoad {
            get {
                return ResourceManager.GetString("Error_QuestionLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа в выходной /праздничный день - обязательное поле.
        /// </summary>
        internal static string HolidayWorkEditModel_Date_Required {
            get {
                return ResourceManager.GetString("HolidayWorkEditModel_Date_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во отработанных часов - обязательное поле.
        /// </summary>
        internal static string HolidayWorkEditModel_Hours_Required {
            get {
                return ResourceManager.GetString("HolidayWorkEditModel_Hours_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Часовая тарифная ставка - обязательное поле.
        /// </summary>
        internal static string HolidayWorkEditModel_Rate_Required {
            get {
                return ResourceManager.GetString("HolidayWorkEditModel_Rate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша учетная запись неактивна. Свяжитесь с администратором..
        /// </summary>
        internal static string Login_AccountInactive {
            get {
                return ResourceManager.GetString("Login_AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно получить версию базы данных ..
        /// </summary>
        internal static string Login_Exception {
            get {
                return ResourceManager.GetString("Login_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильная версия базы данных.Версия приложения {0} ,версия базы данных {1}.Свяжитесь с администратором..
        /// </summary>
        internal static string Login_IncorrectDatabaseVersion {
            get {
                return ResourceManager.GetString("Login_IncorrectDatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильное имя пользователя..
        /// </summary>
        internal static string Login_LoginIncorrect {
            get {
                return ResourceManager.GetString("Login_LoginIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный пароль..
        /// </summary>
        internal static string Login_PasswordIncorrect {
            get {
                return ResourceManager.GetString("Login_PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес электронной почты - обязательное поле.
        /// </summary>
        internal static string LoginRecoveryModel_Email_Required {
            get {
                return ResourceManager.GetString("LoginRecoveryModel_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин - обязательное поле..
        /// </summary>
        internal static string LogOnModel_Login_Required {
            get {
                return ResourceManager.GetString("LogOnModel_Login_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль - обязательное поле.
        /// </summary>
        internal static string LogOnModel_Password_Required {
            get {
                return ResourceManager.GetString("LogOnModel_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_BeginDate_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_BeginDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна, город командировки - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_Country_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_Country_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_EndDate_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Источник финансирования командировки - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_FinancesSource_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_FinancesSource_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цель командировки - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_Goal_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_Goal_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организация, куда командировка - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_Organization_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_Organization_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основание командировки - обязательное поле.
        /// </summary>
        internal static string MissionEditModel_Reason_Required {
            get {
                return ResourceManager.GetString("MissionEditModel_Reason_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль слишком короткий..
        /// </summary>
        internal static string PasswordRegExValidatorText {
            get {
                return ResourceManager.GetString("PasswordRegExValidatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурационная секция &apos;{0}&apos; не найдена..
        /// </summary>
        internal static string Section_NotFound {
            get {
                return ResourceManager.GetString("Section_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-mail для отправки в Биллинг - обязательное поле.
        /// </summary>
        internal static string SettingsModel_BillingEmail_Required {
            get {
                return ResourceManager.GetString("SettingsModel_BillingEmail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP Логин (отправка в биллинг) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_BillingLogin_Required {
            get {
                return ResourceManager.GetString("SettingsModel_BillingLogin_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP Пароль (отправка в биллинг) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_BillingPassword_Required {
            get {
                return ResourceManager.GetString("SettingsModel_BillingPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP порт (отправка в биллинг) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_BillingPort_Required {
            get {
                return ResourceManager.GetString("SettingsModel_BillingPort_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP Сервер (отправка в биллинг) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_BillingSmtp_Required {
            get {
                return ResourceManager.GetString("SettingsModel_BillingSmtp_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь к файлу для загрузки - обязательное поле.
        /// </summary>
        internal static string SettingsModel_DownloadDictionaryFilePath_Required {
            get {
                return ResourceManager.GetString("SettingsModel_DownloadDictionaryFilePath_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-mail для отправки сообщений о произведенном иморте/экспорте - обязательное поле.
        /// </summary>
        internal static string SettingsModel_ExportImportEmail_Required {
            get {
                return ResourceManager.GetString("SettingsModel_ExportImportEmail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-mail для отправки уведомлений - обязательное поле.
        /// </summary>
        internal static string SettingsModel_NotificationEmail_Required {
            get {
                return ResourceManager.GetString("SettingsModel_NotificationEmail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP Логин (отправка уведомлений) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_NotificationLogin_Required {
            get {
                return ResourceManager.GetString("SettingsModel_NotificationLogin_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP Пароль (отправка уведомлений) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_NotificationPassword_Required {
            get {
                return ResourceManager.GetString("SettingsModel_NotificationPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP порт (отправка уведомлений) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_NotificationPort_Required {
            get {
                return ResourceManager.GetString("SettingsModel_NotificationPort_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP Сервер (отправка уведомлений) - обязательное поле.
        /// </summary>
        internal static string SettingsModel_NotificationSmtp_Required {
            get {
                return ResourceManager.GetString("SettingsModel_NotificationSmtp_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата удаления сотрудников, уволенных до - обязательное поле..
        /// </summary>
        internal static string SettingsModel_ReleaseEmployeeDeleteDate_Required {
            get {
                return ResourceManager.GetString("SettingsModel_ReleaseEmployeeDeleteDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь к файлу выгрузки табеля - обязательное поле.
        /// </summary>
        internal static string SettingsModel_UploadTimesheetFilePath_Required {
            get {
                return ResourceManager.GetString("SettingsModel_UploadTimesheetFilePath_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала больничного - обязательное поле.
        /// </summary>
        internal static string SicklistEditModel_BeginDate_Required {
            get {
                return ResourceManager.GetString("SicklistEditModel_BeginDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания больничного - обязательное поле.
        /// </summary>
        internal static string SicklistEditModel_EndDate_Required {
            get {
                return ResourceManager.GetString("SicklistEditModel_EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер больничного листа - обязательное поле.
        /// </summary>
        internal static string SicklistEditModel_SicklistNumber_Required {
            get {
                return ResourceManager.GetString("SicklistEditModel_SicklistNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активный.
        /// </summary>
        internal static string StatusActive {
            get {
                return ResourceManager.GetString("StatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неактивный.
        /// </summary>
        internal static string StatusInactive {
            get {
                return ResourceManager.GetString("StatusInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата  - обязательное поле.
        /// </summary>
        internal static string TimesheetCorrectionEditModel_Date_Required {
            get {
                return ResourceManager.GetString("TimesheetCorrectionEditModel_Date_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Часы  - обязательное поле.
        /// </summary>
        internal static string TimesheetCorrectionEditModel_Hours_Required {
            get {
                return ResourceManager.GetString("TimesheetCorrectionEditModel_Hours_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Часы - обязательное поле.
        /// </summary>
        internal static string TimesheetListModel_Hours_Required {
            get {
                return ResourceManager.GetString("TimesheetListModel_Hours_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестна.
        /// </summary>
        internal static string UnknownDatabaseVersion {
            get {
                return ResourceManager.GetString("UnknownDatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин - обязательное поле.
        /// </summary>
        internal static string UserEditModel_Login_Required {
            get {
                return ResourceManager.GetString("UserEditModel_Login_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль - обязательное поле.
        /// </summary>
        internal static string UserEditModel_Password_Required {
            get {
                return ResourceManager.GetString("UserEditModel_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО - обязательное поле.
        /// </summary>
        internal static string UserEditModel_UserName_Required {
            get {
                return ResourceManager.GetString("UserEditModel_UserName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала отпуска - обязательное поле .
        /// </summary>
        internal static string VacationEditModel_BeginDate_Required {
            get {
                return ResourceManager.GetString("VacationEditModel_BeginDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания отпуска - обязательное поле.
        /// </summary>
        internal static string VacationEditModel_EndDate_Required {
            get {
                return ResourceManager.GetString("VacationEditModel_EndDate_Required", resourceCulture);
            }
        }
    }
}
